name: Update Vercel Deployment

on:
  schedule:
    - cron: '0 19 * * *' # 会在UTC时间的每天晚上7点执行任务，这正好对应北京时间的每天凌晨3点

jobs:
  update-vercel:
    runs-on: ubuntu-latest
    steps:
      - env:
          vercelID: ${{ secrets.vercelID }}
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/$vercelID
