name: Update Vercel Deployment

on:
  schedule:
    - cron: '*/5 * * * *' # 每5分钟运行一次，用于测试

jobs:
  update-vercel:
    runs-on: ubuntu-latest
    steps:
      - env:
          vercelID: ${{ secrets.vercelID }}
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/$vercelID
